In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Activation Function
https://www.youtube.com/watch?v=icZItWxw7AI&list=PLeo1K3hjS3uu7CxAacxVndI4bE_o3BDtO&index=8

In [2]:
import math

def sigmoid(x):
    return 1/ (1 + math.exp(-x))

In [7]:
sigmoid(100)
sigmoid(1)
sigmoid(-1)
sigmoid(-56)
sigmoid(0.5)

1.0

0.7310585786300049

0.2689414213699951

4.780892883885469e-25

0.6224593312018546

In [17]:
def tanh(x):
    return (math.exp(x) - math.exp(-x)) /(math.exp(x) + math.exp(-x))


In [19]:
tanh(-56)
tanh(50)
tanh(1)

-1.0

1.0

0.7615941559557649

In [20]:
def relu(x):
    return max(0, x)

In [22]:
relu(8)
relu(-100)

8

0

In [23]:
def leaky_relu(x):
    return max(0.1 * x, x)

In [24]:
leaky_relu(-100)

-10.0

### Derivative
https://www.mathsisfun.com/calculus/derivatives-rules.html
https://www.mathsisfun.com/calculus/derivatives-partial.html


### Matrix

https://www.mathsisfun.com/algebra/matrix-introduction.html

In [26]:
import numpy as np

revenue = np.array([[100,200,220],[24,36,40],[12,18,20],])
expense = np.array([[80,90,100],[10,16,20],[8,10,10],])


In [29]:
profit = revenue- expense 
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [34]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50], [5,10,15], [2,5,7]])
units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [32]:
price_per_unit * units    # broadcast

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [36]:
np.dot(price_per_unit, units)    # dot product

array([34400, 50000, 64400])

In [35]:
revenue = np.array([[200,220, 250], [68,79,105],[110,140,180],[80,85,90]])
revenue_rupee = 75 * revenue
revenue_rupee

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [41]:
price_per_unit = np.array([20,30,15])
units = np.array([[50, 60,25],[10,13,5],[40,70,52]])
np.dot(price_per_unit, units)

array([1900, 2640, 1430])