##### The basic steps to implement Linear Regression
1. Import the packages and classes you need;
2. Provide data to work with and eventually do appropriate cleaning.
3. Create a regression model and fit it with existing data;
4. Check the results of model fitting to know whether the model is satisfactory;
5. Apply the model for predictions.

#### I. Linear Regression

In [1]:
# step 1 import the packages and classes
import numpy as np
from sklearn.linear_model import LinearRegression


In [2]:
# step 2 provide the data
# array.reshape(-1, 1) is to make the array two-dimensional,
# to have one column and as many rows as necesary.
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1, 1)
y = np.array([5, 20, 14, 32, 22, 38])
display(x, y)

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

array([ 5, 20, 14, 32, 22, 38])

In [3]:
x.shape

(6, 1)

In [4]:
y.shape    # y has a single dimension, 

(6,)

In [5]:
# step 3 create a model and fit it
model = LinearRegression()

#### LinearRegression provides several optional prarmeters to optimize
1. fit_intercept is a Boolean (True by default) to decide whether to calculate the intercept b0 (True) or consider it equal to zero(False).
2. normalize is a Boolean (False by default) to decide whether to normalize the input variables (True) or not (False).
3. copy_x is a Boolean (True by default) to decide whether to copy (True) or overwrite the input variables (False).
4. n_jobs is an integer or None (default) to represent the # of jobs used in parallel computation. None = one job, -1 = to use all processes

In [6]:
# use default values of all parameters
# to start using the model.
# to calculate the optimal values of weights b0 and b1
# using the existing input and output (x and y) as the arguments.
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
# step 4 get results
# the arguments of .score() are also the predictor x and regresson y,
# and the return value is R^2
r_sq = model.score(x, y)
r_sq        # coefficient of determination

0.715875613747954

In [8]:
model.intercept_    # represents the coefficient, b0

5.633333333333329

In [9]:
model.coef_        # represents the b1

array([0.54])

In [10]:
# step 5 predict
x_new = np.arange(5).reshape(-1, 1)
y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

#### II. Multiple Linear Regression

In [11]:
# step 1
import numpy as np
from sklearn.linear_model import LinearRegression

In [12]:
# step 2
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
display(x, y)

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [13]:
# step 3
model2 = LinearRegression()
model2.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
# step 4
r_sq = model2. score(x, y)
r_sq          # coefficient of determination


0.8615939258756776

In [15]:
display(model2. intercept_, model2.coef_)   # intercept and coefficient

5.52257927519819

array([0.44706965, 0.25502548])

In [17]:
# step 5
y_pred = model2.predict(x)
y_pred

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

In [18]:
y_pred = model2.intercept_ + np.sum(model2.coef_ * x, axis = 1)
y_pred

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

In [19]:
# predict new value
x_new = np.arange(10).reshape((-1, 2))
x_new


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
y_new = model2.predict(x_new)
y_new.reshape((-1,1))

array([[ 5.77760476],
       [ 7.18179502],
       [ 8.58598528],
       [ 9.99017554],
       [11.3943658 ]])

#### III. Polynomial Regression 
There is only one extra step: to transform the array of inputs to include non-linear terms such as x^2

In [25]:
# step 1
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [26]:
# step 2a provide data
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])
display(x, y)

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

array([15, 11,  2,  8, 25, 32])

In [27]:
# step 2b transform input data
transformer = PolynomialFeatures(degree = 2, include_bias = False)

PolynomialFeatures provide several parameters:
1. degree is an integer (2 by default) that provides the degree of the polynomial regression function.
2. interaction_only is a Boolean (False by default) that decides whether to include only interaction features (True) or all features (False).
3. include_bias is a Boolean (True by default) that decides whether to include bias (intercept) column of ones (True) or not (False).


In [29]:
# before applying transformer, you need to fit it
transformer.fit(x)

# once transformer is fitted, it's ready to create a new , modified input
# .transform() takes the input array as the argument and returns the modified array.
x_ = transformer.transform(x)
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [31]:
# step 3 create a model and fit it
model3 = LinearRegression()
model3.fit(x_, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
# step 4 get results
r_sq = model3.score(x_, y)
r_sq

0.8908516262498564

In [33]:
display(model3.intercept_, model3.coef_)

21.372321428571425

array([-1.32357143,  0.02839286])

#### New transformation and regression 

In [34]:
# new step 2b, different transformation and regression arguments
x_ = PolynomialFeatures(degree = 2, include_bias = True).fit_transform(x)
x_
# to obtain the new input array x_ with the additional leftmost column 
# containing only ones. This column corresponds to the intercept.

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [36]:
# step 3 The intercept is already included with the leftmost
# column of ones, and don't need to include it again when 
# creating the instance of LinearRegression.
model4 = LinearRegression(fit_intercept = False).fit(x_, y)

In [37]:
# step 4
r_sq = model4.score(x_, y)
r_sq

0.8908516262498565

In [38]:
model4. intercept_

0.0

In [39]:
model4.coef_

array([21.37232143, -1.32357143,  0.02839286])

In [40]:
# step 5
y_pred = model4.predict(x_)
y_pred

array([15.46428571,  7.90714286,  6.02857143,  9.82857143, 19.30714286,
       34.46428571])

#### An example

In [44]:
# Step 1: Import packages
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Step 2a: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

# Step 2b: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

# Step 3: Create a model and fit it
model5 = LinearRegression().fit(x_, y)

# Step 4: Get Results
r_sq = model5.score(x_, y)
intercept, coefficients = model5. intercept_, model5.coef_
display(r_sq, intercept, coefficients)

# Step 5: Predict
y_pred = model5.predict(x_)
display(y_pred)

0.9453701449127822

0.8430556452395734

array([ 2.44828275,  0.16160353, -0.15259677,  0.47928683, -0.4641851 ])

array([ 0.54047408, 11.36340283, 16.07809622, 15.79139   , 29.73858619,
       23.50834636, 39.05631386, 41.92339046])

#### There are six coefficients (including the intercept) for regression function
𝑓(𝑥₁, 𝑥₂) = 𝑏₀ + 𝑏₁𝑥₁ + 𝑏₂𝑥₂ + 𝑏₃𝑥₁² + 𝑏₄𝑥₁𝑥₂ + 𝑏₅𝑥₂².

#### IV. Advanced LinearRegressoin with statsmodels package

In [46]:
# step 1
import numpy as np
import statsmodels.api as sm

In [47]:
# step 2a
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
x, y

(array([[ 0,  1],
        [ 5,  1],
        [15,  2],
        [25,  5],
        [35, 11],
        [45, 15],
        [55, 34],
        [60, 35]]), array([ 4,  5, 20, 14, 32, 22, 38, 43]))

In [48]:
# step 2b: to add the column of ones to the inputs if you want statmodels 
# to calculate the intercept b0. 
x = sm.add_constant(x)
display(x, y)

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [54]:
# step 3: the regression model based on Ordinary Least Squares is 
# an instance of the class statmodels.regression.linear_model.OLS
model6 = sm.OLS(y, x)
results = model6.fit()

In [55]:
# step 4 get results
display(results.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Sun, 26 Apr 2020   Prob (F-statistic):            0.00713
Time:                        15:08:35   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.268      -5.867      16.912
x1             0.4471      0.285      1.567      0.178      -0.286       1.180
x2             0.2550      0.453      0.563      0.598      -0.910       1.420
==============================================================================
Omnibus:                        0.561   Durbin-Watson:                   3.268
Prob(Omnibus):                  0.755   Jarque-Bera (JB):                0.534
Skew:                           0.380   Prob(JB):                        0.766
Kurtosis:                       1.987   Cond. No.                         80.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [53]:
r_sq = results.rsquared     # coefficient of determination
r_sq

0.8615939258756777

In [57]:
r_sq_adj = results.rsquared_adj    # adjusted coefficient of determination.
r_sq_adj    # R^2 corrected according to the # of input features

0.8062314962259488

In [58]:
reg_coef = results.params    # regression coefficients, refers the array with b0, b1, b2 respectively
reg_coef

array([5.52257928, 0.44706965, 0.25502548])

In [61]:
# step 5: predict
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
y_new = results.predict(x_new)
display(x_new, y_new)

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.],
       [1., 6., 7.],
       [1., 8., 9.]])

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

##### Linear Regression is sometimes not appropriate, especially for non-linear models of high complexity.

Fortunately, there are other regression techniques suitable for the cases where linear regression doesn’t work well. Some of them are support vector machines, decision trees, random forest, and neural networks.

The package scikit-learn provides the means for using other regression techniques in a very similar way to what you’ve seen. It contains the classes for support vector machines, decision trees, random forest, and more, with the methods .fit(), .predict(), .score() and so on.