In [5]:
import numpy as np

print(np.__version__)
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
print(a, a.dtype)
print(b, b.dtype)

1.16.5
[1 2 3 4 5 6] int32
[ 7  8  9 10 11 12] int32


In [4]:
B = np.array((5,6,7.8,3))
B.dtype

dtype('float64')

In [6]:
a[0]

1

In [7]:
a[0] = 7.4
a

array([7, 2, 3, 4, 5, 6])

In [8]:
# the element of numpy array can be changed. But the array's dtype is inchangeable.
a.dtype


dtype('int32')