In [1]:
import numpy as np

np.__version__

'1.18.1'

### Create and View Data in NumPy Array

In [4]:
# each item's memory size
a = np.array([1,2,3])
print(a.itemsize)
a = np.array([1,2,3], dtype = 'int16')
print(a.itemsize)

4
2


In [8]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b.dtype)
print(b.itemsize)

float64
8


In [9]:
# number of items
print(a.size)
print(b.size)

3
6


In [10]:
# total memory size (1), in bytes
print(a.size * a.itemsize)
print(b.size * b.itemsize)

6
48


In [11]:
# total memory size (2), in bytes
print(a.nbytes)
print(b.nbytes)

6
48


### Access and Modify items in NumPy Array

In [13]:
a = np.array([[1,2,3,4,5,6,7], [7,6,5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 3, 2, 1]])

In [14]:
print(a[1,1])
print(a[1,-1])

6
1


In [15]:
print(a[0,:])
print(a[:,1])

[1 2 3 4 5 6 7]
[2 6]


In [17]:
a[0,1:6:2]

array([2, 4, 6])

In [19]:
a[1,1:-1:2]

array([6, 4, 2])

In [20]:
a[:,2] = 66
a

array([[ 1,  2, 66,  4,  5,  6,  7],
       [ 7,  6, 66,  4,  3,  2,  1]])

In [21]:
a[:,2] = [6,9]
a

array([[1, 2, 6, 4, 5, 6, 7],
       [7, 6, 9, 4, 3, 2, 1]])

In [22]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
b[0,1,1]

4

In [24]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
b[:,1,:] = [[10,10],[10,10]]
b

array([[[ 1,  2],
        [10, 10]],

       [[ 5,  6],
        [10, 10]]])