### Basic

In [1]:
import numpy as np

print(np.__version__)
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
print(a, a.dtype)
print(b, b.dtype)

1.18.1
[1 2 3 4 5 6] int32
[ 7  8  9 10 11 12] int32


In [2]:
B = np.array((5,6,7.8,3))
B.dtype

dtype('float64')

In [3]:
a[0]

1

In [4]:
a[0] = 7.4
a

array([7, 2, 3, 4, 5, 6])

In [5]:
# the element of numpy array can be changed. But the array's dtype is inchangeable.
a.dtype


dtype('int32')

In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)
print(a[0])
print(a[1])
print(a[0][1])
print(a[1][2])

2
[1 2 3]
[4 5 6]
2
6


In [7]:
b = np.array([[[1,2,3], [4,5,6]], [[4,5,6], [1,2,3]]])
print(b.ndim)
print(b.shape)
print(b.shape[0], b.shape[1], b.shape[2])

3
(2, 2, 3)
2 2 3


In [8]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 常量

np.nan, np.NaN, np.NAN表示空值
**但是他们并不相等**

In [7]:
import numpy as np

print(np.nan == np.nan)    #False
print(np.nan != np.nan)    #True
print(np.nan != np.NAN)    #True

False
True
True


np.isnan(x, *args, *kwargs) Test element-wise for NaN and return result as a boolean array.

In [10]:
import numpy as np
x = np.array([1,1,8,np.nan, 10])
print(x)
y = np.isnan(x)
print(y)
z = np.count_nonzero(y)
print(z)

[ 1.  1.  8. nan 10.]
[False False False  True False]
1


numpy.inf 表示正无穷大
numpy.pi 表示圆周率pi
numpy.e 表示自然常数e

### Numpy基本数据类型

|类型       |备注  |说明   |
|----------|----|------|
|bool_=bool8|8位|布尔类型|
|int8 = byte|8位|整型|
|int16=short|16位|整型|
|int32=intc|32位|整型|
|int_=int64=long=int0=intp|64位|整型|
|uint8=ubyte|8位|无符号整数|
|uint16=ushort|16位|无符号整数|
|uint32=uintc|32位|无符号整数|
|uint64=uintp=unit0=uint|64位|无符号整数|
|float16=half|16位|浮点型|
|float32=single|32位|浮点型|
|float_=float64=double|64位|浮点型|
|str =*unicode* = str0=unicode|   |Unicode字符串|
|datetime64    |  |日期时间类型|
|timedelta64   |   | 表示二个时间之间的间隔|


**每个内建类型都有一个唯一定义它的字符代码**

|字符   |对应类型  |备注  |
|------|---------|-----|
|b      |boolean |‘b1’|
|i     |signed integer|'i1','i2','i4', 'i8'|
|u     |unsigned integer|'u1', 'u2', 'u4', 'u8'|
|f     |floating-point| 'f2', 'f4', 'f8'|
|c     |complex floating-point|         |
|m     |timedelta64   |表示两个时间的间隔  |
|M     |datetime64    |日期事件类型       |
|O     |object        |                 |
|S     |(byte-)string |S3表示长度为3的字符串|
|U     |Unicode       |Unicode字符串     |
|V     |Void          |                 |

In [19]:
import numpy as np

a = np.dtype('b1')
print(a.type)    # <class 'numpy.bool_'>
print(a.itemsize)    #1

a = np.dtype('i1')
print(a.type)    # <class 'numpy.int8'>
print(a.itemsize)    #1
a = np.dtype('i2')
print(a.type)    # <class 'numpy.int16'>
print(a.itemsize)    #2
a = np.dtype('i4')
print(a.type)    # <class 'numpy.int32'>
print(a.itemsize)    #4
a = np.dtype('i8')
print(a.type)    # <class 'numpy.int64'>
print(a.itemsize)    #8

a = np.dtype('u1')
print(a.type)    # <class 'numpy.uint8'>
print(a.itemsize)    #1
a = np.dtype('u2')
print(a.type)    # <class 'numpy.uint16'>
print(a.itemsize)    #2
a = np.dtype('u4')
print(a.type)    # <class 'numpy.uint32'>
print(a.itemsize)    #4
a = np.dtype('u8')
print(a.type)    # <class 'numpy.uint64'>
print(a.itemsize)    #8

a = np.dtype('f2')
print(a.type)    # <class 'numpy.float16'>
print(a.itemsize)    #2
a = np.dtype('f4')
print(a.type)    # <class 'numpy.float32'>
print(a.itemsize)    #4
a = np.dtype('f8')
print(a.type)    # <class 'numpy.float64'>
print(a.itemsize)    #8

a = np.dtype('S')
print(a.type)    # <class 'numpy.bytes_'>
print(a.itemsize)    #0
a = np.dtype('S3')
print(a.type)    # <class 'numpy.bytes_'>
print(a.itemsize)    #3

a = np.dtype('U3')
print(a.type)    # <class 'numpy.str_'>
print(a.itemsize)    #12


<class 'numpy.bool_'>
1
<class 'numpy.int8'>
1
<class 'numpy.int16'>
2
<class 'numpy.int32'>
4
<class 'numpy.int64'>
8
<class 'numpy.uint8'>
1
<class 'numpy.uint16'>
2
<class 'numpy.uint32'>
4
<class 'numpy.uint64'>
8
<class 'numpy.float16'>
2
<class 'numpy.float32'>
4
<class 'numpy.float64'>
8
<class 'numpy.bytes_'>
0
<class 'numpy.bytes_'>
3
<class 'numpy.str_'>
12


In [24]:
class iinfo(object):
    def __init__(self, int_type):
        pass
    def min(self):
        pass
    def max(self):
        pass

import numpy as np

ii16 = np.iinfo(np.int16)
print(ii16.min)    #-32768
print(ii16.max)    #32767

ii32 = np.iinfo(np.int32)
print(ii32.min)    #-2147483648
print(ii32.max)    #2147483647

-32768
32767
-2147483648
2147483647


In [26]:
class finfo(object):
    def __init__(self, int_type):
        pass
    def min(self):
        pass
    def max(self):
        pass

import numpy as np

ff16 = np.finfo(np.float16)
print(ff16.bits)
print(ff16.min)    #-65500
print(ff16.max)    #65500
print(ff16.eps)

ff32 = np.finfo(np.float32)
print(ff32.bits)   #32
print(ff32.min)    #-3.4028235e+38
print(ff32.max)    #3.4028235e+38
print(ff32.eps)    #1.1920929e-07

16
-65500.0
65500.0
0.000977
32
-3.4028235e+38
3.4028235e+38
1.1920929e-07


### INDEX ARRAY

In [2]:
arr = np.random.randint(0,10,(5,))
print(arr)
index = np.where(arr<5)
print(index)

[4 3 5 3 3]
(array([0, 1, 3, 4], dtype=int64),)


In [10]:
A[[1,3,7]]

array([1, 3, 7])

In [11]:
A = np.random.permutation(np.arange(10))
A

array([3, 9, 5, 6, 2, 1, 7, 4, 0, 8])

In [12]:
A[[4,3,8]]

array([2, 6, 0])

In [13]:
A[[True, True, False, True, False, False,True, False, True, True]]


array([3, 9, 6, 7, 0, 8])

In [14]:
A[A<4]

array([3, 2, 1, 0])

In [17]:
A[(A>4)]

array([9, 5, 6, 7, 8])

In [ ]:
B = np.random.rand(1000000)
%timeit np.sum(B)

In [ ]:
%timeit B.sum()

In [ ]:
%timeit sum(B)


In [ ]:
%%timeit
s = 0
for x in B:
    s += x

**astype() to convert to another type **

In [19]:
numeric_strings = np.array(['1.2', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.2, -9.6, 42. ])

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float)
float_arr.dtype

dtype('float64')

In [23]:
float_arr

array([1., 2., 3., 4., 5.])

In [24]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([4391013, 7143535, 5439580, 6684769, 4391013, 7143535, 7471184,
       7209065], dtype=uint32)