In [1]:
# 1. numpy alias np
import numpy as np

# 2. show numpy version and configuration
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/work2/anaconda3/envs/py38\\Library\\include']
None


In [5]:
# 3. create an empty array with length=10
arr = np.zeros(10)
print(arr)
# 4. get array size
print("{} bytes".format(arr.size * arr.itemsize))    # 10 * 8

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80 bytes


In [7]:
# 5. show add function doc
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [8]:
# 6. create an empty array with length 10 but fifth value is 1
arr = np.zeros(10)
arr[4] = 1 
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# 7. create an array with value from 10 to 49
arr = np.arange(10,50)
print(arr)

# 8. reverse an array
arr = arr[::-1]
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# 9. create an array 3x3 with 0 to 8
arr = np.arange(0, 9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# 10. get a non-zero item index of array [1,2,0,0,4,0] 
arr = [1,2,0,0,4,0]
idx = np.nonzero(arr)    # a tuple
print(idx)

(array([0, 1, 4], dtype=int64),)


tuple

In [13]:
# 11. create 3x3 identity matrix
I = np.eye(3)
I 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])