https://mp.weixin.qq.com/s/RsRbV9dleqkzdzy2xrcYMQ

### axis=0与axis =1的含义
axis指的就是“**轴**”，轴的取值一般是0,1,2,...其中0表示最高维，1表示次高维，...，依次推算下去。

以二维结构为例：

**当axis=0**, 由于0代表最高维度，因此数据中高维发生变化，而低维没有变化（但是低维相同）的数据，会自动成为一组。如:

a\[0][0],a[1][0],a[2][0],...,a[*][0]成为一组

a[0][1],a[1][1],a[2][1],...,a[*][1]成为一组

...

**当axis=0的时候，相当于沿着列的方向，进行函数运算**。

**当axis=1**, 由于1代表次高维度，因此数据中低维发生变化，而高维没有变化（但是高维相同）的数据，会自动成为一组。如:

a[0][0],a[0][1],a[0][2],...,a[0][*]成为一组

a[1][0],a[1][1],a[1][2],...,a[1][*]成为一组

...

**当axis=1的时候，相当于沿着行的方向，进行函数运算**。


In [3]:
import numpy as np

x = np.arange(16).reshape(4,4)
xa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
display(x.sum(axis=0))
display(x.sum(axis=1))

array([24, 28, 32, 36])

array([ 6, 22, 38, 54])