### Basic

In [1]:
import numpy as np

print(np.__version__)
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
print(a, a.dtype)
print(b, b.dtype)

1.18.1
[1 2 3 4 5 6] int32
[ 7  8  9 10 11 12] int32


In [2]:
B = np.array((5,6,7.8,3))
B.dtype

dtype('float64')

In [3]:
a[0]

1

In [4]:
a[0] = 7.4
a

array([7, 2, 3, 4, 5, 6])

In [5]:
# the element of numpy array can be changed. But the array's dtype is inchangeable.
a.dtype


dtype('int32')

In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)
print(a[0])
print(a[1])
print(a[0][1])
print(a[1][2])

2
[1 2 3]
[4 5 6]
2
6


In [7]:
b = np.array([[[1,2,3], [4,5,6]], [[4,5,6], [1,2,3]]])
print(b.ndim)
print(b.shape)
print(b.shape[0], b.shape[1], b.shape[2])

3
(2, 2, 3)
2 2 3


In [8]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

INDEX ARRAY

In [2]:
arr = np.random.randint(0,10,(5,))
print(arr)
index = np.where(arr<5)
print(index)

[4 3 5 3 3]
(array([0, 1, 3, 4], dtype=int64),)


In [10]:
A[[1,3,7]]

array([1, 3, 7])

In [11]:
A = np.random.permutation(np.arange(10))
A

array([3, 9, 5, 6, 2, 1, 7, 4, 0, 8])

In [12]:
A[[4,3,8]]

array([2, 6, 0])

In [13]:
A[[True, True, False, True, False, False,True, False, True, True]]


array([3, 9, 6, 7, 0, 8])

In [14]:
A[A<4]

array([3, 2, 1, 0])

In [17]:
A[(A>4)]

array([9, 5, 6, 7, 8])

In [ ]:
B = np.random.rand(1000000)
%timeit np.sum(B)

In [ ]:
%timeit B.sum()

In [ ]:
%timeit sum(B)


In [ ]:
%%timeit
s = 0
for x in B:
    s += x

**astype() to convert to another type **

In [19]:
numeric_strings = np.array(['1.2', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.2, -9.6, 42. ])

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float)
float_arr.dtype

dtype('float64')

In [23]:
float_arr

array([1., 2., 3., 4., 5.])

In [24]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([4391013, 7143535, 5439580, 6684769, 4391013, 7143535, 7471184,
       7209065], dtype=uint32)