In [1]:
import numpy as np

def myfunc(a,b):
    """Return a-b if a>b, otherwise returns a+b"""
    if a > b:
        return a-b
    else:
        return a+b 

vfunc = np.vectorize(myfunc)

In [2]:
vfunc([1,2,3,4],2)

array([3, 4, 1, 2])

In [4]:
vfunc = np.vectorize(myfunc, doc = "Vectorized myfunc")
vfunc.__doc__

'Vectorized myfunc'

In [7]:
# Output type is determined by the type of the first input type
# unless changed by the 'otypes' parameter in np.vectorize() func

out = vfunc([2,3,4,5],3)
type(out[0])
vfunc = np.vectorize(myfunc, otypes=[float])
out = vfunc([4,5,6,7],5)
type(out[0])
out 

array([ 9., 10.,  1.,  2.])

In [14]:
# 'excluded' parameter can prevent some parameters vectorized,
# for example, the coefficients of polynomial
def mypolyval(p,x):
    _p = list(p)
    res = _p.pop(0)
    print(res,x)
    print('loop:')
    while _p:
        #res = res * x + _p.pop(0)
        a = res * x
        b = _p.pop(0)
        res = a + b
        print(x,a,b,res)
    return res 

vpolyval = np.vectorize(mypolyval, excluded=['p'])
vpolyval(p=[1,2,3],x=[0,1])

1 0
loop:
0 0 2 2
0 0 3 3
1 0
loop:
0 0 2 2
0 0 3 3
1 1
loop:
1 1 2 3
1 3 3 6


array([3, 6])

In [16]:
x = np.array([1.,1.1, 1.2, 1.3, 1.4,-2.2])
f2 = np.vectorize(np.int)
f2(x)

array([ 1,  1,  1,  1,  1, -2])