### What is PYTORCH?

It's a Python-based scientific computing package targeted at two sets of audiences:
- A replacement for Numpy to use the power of GPUs;
- a deep learning research platform that provides maximum flexibility and speed.


#### Getting Started

##### Tensors
Tensors are similar to Numpy's **ndarrays**, with the addition being that Tensors can also be used on a GPU to accelerate computing.


In [1]:
from __future__ import print_function
import torch

In [2]:
 # Construct a 5x3 matrix, uninitialized
x = torch.empty(5,3)
print(x)

tensor([[-1.1580e+04,  7.4969e-43, -1.1497e+04],
        [ 7.4969e-43, -1.1498e+04,  7.4969e-43],
        [-1.1498e+04,  7.4969e-43, -1.1498e+04],
        [ 7.4969e-43, -1.1498e+04,  7.4969e-43],
        [-1.1499e+04,  7.4969e-43, -1.1499e+04]])


In [3]:
# Construct a randomily initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.4816, 0.1342, 0.4498],
        [0.9727, 0.0541, 0.2833],
        [0.2268, 0.4312, 0.5814],
        [0.9234, 0.2686, 0.0709],
        [0.6941, 0.2600, 0.5004]])


In [6]:
# construct a matrix filled zeros and of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
print(x.dtype)

torch.int64


In [8]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
# to create a tensor based on an existing tensor
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


In [23]:
# get the size
print(x.size())

torch.Size([5, 3])


torch.Size is a tuple.

##### Operations

In [11]:
y = torch.zeros(5,3)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# syntax 1
print(x+y)


tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


In [13]:
# syntax 2
print(torch.add(x,y))

tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


In [14]:
# providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


In [17]:
y=torch.empty(5,3)
print(y)

tensor([[8.9082e-39, 1.0102e-38, 1.0102e-38],
        [8.4490e-39, 8.9082e-39, 9.1837e-39],
        [1.0561e-38, 1.0010e-38, 1.0469e-38],
        [9.2755e-39, 9.7347e-39, 9.6429e-39],
        [8.7245e-39, 1.0194e-38, 9.0919e-39]])


In [18]:
# in-place
# add x to y
y.add_(x)
print(y)

tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


Any operation that mutates a tensor in-place is post-fixed with an _.
For example, x.copy_(y), x.t_() will change x.

In [19]:
print(x)

tensor([[-1.5955, -0.8056, -0.9179],
        [ 0.6028, -0.7557,  1.3288],
        [ 1.4277, -1.2872, -1.0632],
        [-0.6057,  0.8459, -0.4923],
        [ 0.2124,  0.0655, -2.2103]])


In [20]:
print(x[:,1])

tensor([-0.8056, -0.7557, -1.2872,  0.8459,  0.0655])


In [27]:
# torch.view to resize/reshape tensor
x = torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [28]:
x = torch.randn(1)
print(x)

tensor([-1.6431])


In [29]:
print(x.item())

-1.6431418657302856


docs at https://pytorch.org/docs/stable/torch.html

#### Numpy Bridge

Converting a Torch Tensor to a Numpy array and vice versa is a breeze.

The Torch Tensor and Numpy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

##### Converting a Torch Tensor to a Numpy Array


In [40]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [41]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [42]:
# tensor and numpy array change in value
a.add_(1)    # change the tensor will change the numpy automatically
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting Numpy Array to Torch Tensor

In [43]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)    # change the numpy will change the tensor automatically
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [44]:
np.add(a,-3, out=a)
print(a)
print(b)

[-1. -1. -1. -1. -1.]
tensor([-1., -1., -1., -1., -1.], dtype=torch.float64)


**All the Tensors on the CPU except a CharTensor support converting to NumPy and back.**

#### CUDA Tensors

In [45]:
torch.cuda.is_available()

C:\work2\anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


False

Tensors can be moved onto any device using the **.to()** method.

let us run this cell only if CUDA is available
We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
 
Out:
tensor([1.3417], device='cuda:0')
tensor([1.3417], dtype=torch.float64)