In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### 张量的创建

#### 直接创建
torch.tensor()
功能：从data创建tensor
参数：
data: 数据，可以是list, numpy

dtype: 数据类型，默认与data一致

device: 所在设备, cuda/cpu

requires_grad: 是否需要梯度

pin_memory: 是否存于锁页内存



In [2]:
import torch
import numpy as np

arr = np.ones((3,4))
print(arr.dtype)
t = torch.tensor(arr)
print(t)

float64
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


#### 从numpy创建tensor
torch.from_numpy(ndarray)

功能：从numpy创建tensor

从torch.from_numpy()创建的tensor与原ndarray**共享内存**，当修改其中的一个数据，另一个也修改。

In [3]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])
t = torch.from_numpy(arr)
arr
type(arr)
t 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy.ndarray

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [4]:
arr[0,0]=100
arr
t 

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

tensor([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]], dtype=torch.int32)

In [5]:
t[-1,-1] = 200
t
arr 

tensor([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8, 200]], dtype=torch.int32)

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8, 200]])

#### 依据数值创建
torch.zeros()

功能：依size创建全0张量

参数：

size: 张量的形状，如(3,3), (3, 224, 224)

out: 输出的张量

dtype: 数据类型

layout: 内存中的布局形式，有strided, sparse_coo等

device: cpu/cuda

requires_grad 是否需要梯度

In [6]:
out_t = torch.tensor([1])
# out_t = out_t * 2
t = torch.zeros((3,3), out=out_t)
t 
print(id(t), id(out_t))
id(t) == id(out_t)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

2698378581312 2698378581312


True

**torch.zeros_like()**

功能：依input形状创建全0张量

input：创建与input同形状的全0张量

dtype: 数据类型

layout: 内存中布局形式

device:

requires_grad:

**torch.ones()**

**torch.ones_like()**

**torch.full()**

**torch.full_like()**

参数：

size: 张量的形状，如(3,3)

fill_value: 张量的值

In [7]:
t = torch.full((5,5), 55)
t 

tensor([[55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55]])

**torch.arange()**

功能： 创建等差的**1维张量**

数值区间为\[start, end\), step 默认为1


In [8]:
t = torch.arange(2,20,2)
t 

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

**torch.linspace()

功能：创建均分数列

数值区间为\[start,end\], steps为数列长度

In [9]:
t = torch.linspace(2,20,12)
t 

tensor([ 2.0000,  3.6364,  5.2727,  6.9091,  8.5455, 10.1818, 11.8182, 13.4545,
        15.0909, 16.7273, 18.3636, 20.0000])

**torch.logspace()**

功能：创建对数均分的**1维张量**

数值区间\[start,end\], 数列长度为steps,底为base，默认为10

**torch.eye()**

功能：创建单位对角矩阵**(2维方阵)**


#### 依概率分布创建张量

torch.normal()

生成正态分布

mean: 均值

std: 标准差

四种模式：
mean 标量 std 标量

mean 标量 std 张量

mean 张量 std 标量

mean 张量 std 张量

In [10]:
# mean: 张量 std: 张量
mean = torch.arange(1,5, dtype = torch.float)
std = torch.arange(1,5, dtype = torch.float)
# out_t = torch.tensor([0.,1.,2.,3.])
t_normal = torch.normal(mean, std) 
print("mean:{}\t std:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])	 std:tensor([1., 2., 3., 4.])
tensor([1.8900, 6.5149, 3.4097, 2.7031])


In [11]:
# mean 标量 std 标量, 此时要加一个参数size

t_normal = torch.normal(0., 1., size=(4,))
t_normal

tensor([-1.5645,  0.1384, -0.0393,  0.4202])

In [12]:
# mean 张量， std 标量

mean = torch.arange(1,5, dtype = torch.float)
std = 1
t_normal = torch.normal(mean, std)
t_normal

tensor([-0.0873,  3.5278,  3.7007,  3.7487])

**torch.randn()**

**torch.randn_like()**

功能: 生成标准正态分布

参数： 
size: 张量的形状


**torch.rand()**

**torch.rand_like()**

功能：在区间\[0,1\)上，生成**均匀分布**

**torch.randint()**

**torch.randint_like()**

功能：在区间\[low,high\)上，生成**整数均匀分布**

size： 张量的形状

**torch.randperm(n)**

功能：生成从0到n-1的随机数列

n: 张量的长度

**torch.bernoulli()**

功能：以input维概率，生成伯努利分布（0-1分布，两点分布）



### 张量的操作

#### 拼接与切分

**torch.cat()**

将张量按维度dim进行拼接

tensors: 张量序列

dim: 要拼接的维度

**torch.stack()**

在**在新创建的维度dim**上进行拼接

tensors: 张量序列

dim: 要拼接的维度


In [13]:
t0 = torch.zeros((2,3))
t1 = torch.ones((2,3))

t_0 = torch.cat([t0,t1, t0], dim=0)
t_1 = torch.cat([t0,t1, t0], dim=1)
t_0
t_0.shape
t_1
t_1.shape

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.Size([6, 3])

tensor([[0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0.]])

torch.Size([2, 9])

In [14]:
t = torch.zeros((2,3))

t_stack = torch.stack([t,t], dim=0)
t_stack
t_stack.shape

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

torch.Size([2, 2, 3])

**torch.chunk()**

将张量按维度dim进行平均切分

返回张量列表

若不能整除，最后一份张量的大小小于其他张量


In [15]:
t = torch.ones((2,7))
list_of_tensors = torch.chunk(t, dim=1, chunks = 3)

for idx, t in enumerate(list_of_tensors):
    print("No.{} tensor: shape is {}".format(idx+1, t.shape))

No.1 tensor: shape is torch.Size([2, 3])
No.2 tensor: shape is torch.Size([2, 3])
No.3 tensor: shape is torch.Size([2, 1])


**torch.split()**

将张量按维度dim进行切分

返回张量列表

tensor： 要切分的张量

split_size_or_sections: 为int时，表示每一份的长度；为list时，按list元素切分



In [16]:
a = torch.ones((2,5))
list_of_tensors = torch.split(a, dim=1, split_size_or_sections = [0,2,3])

for idx, t in enumerate(list_of_tensors):
    print("No.{} tensor: shape is {}".format(idx+1, t.shape))

No.1 tensor: shape is torch.Size([2, 0])
No.2 tensor: shape is torch.Size([2, 2])
No.3 tensor: shape is torch.Size([2, 3])


#### 张量索引

**torch.index_select()**

在维度dim上，按index索引数据

返回按index索引数据拼接的张量


In [17]:
t = torch.randint(0,9, size=(3,3))
idx = torch.tensor([0,2], dtype=torch.long)    # 数据类型只能时torch.long, 不能为torch.float
t_select = torch.index_select(t, dim=0, index=idx)
print("t:{}\nt_select:{}".format(t, t_select))

t:tensor([[6, 4, 6],
        [4, 2, 0],
        [7, 7, 4]])
t_select:tensor([[6, 4, 6],
        [7, 7, 4]])


**torch.masked_select()**

按mask中的True进行索引

返回一维张量。因为不能确定True的个数，因此也不能确定返回的形状

input: 要索引的张量

mask：与mask同形状的布尔类型张量

In [18]:
t = torch.randint(0,9, size=(3,3))
mask = t.ge(5)  #ge, gt, le, lt
t_select = torch.masked_select(t, mask)
print("t:{}\nt_select:{}".format(t, t_select))

t:tensor([[1, 3, 8],
        [8, 4, 0],
        [4, 0, 8]])
t_select:tensor([8, 8, 8])


#### 张量变换

**torch.reshape()**

变换张量形状

当张量在内存中是连续时，新张良与input共享数据内存



In [19]:
t = torch.randperm(8)
t_reshaped = torch.reshape(t, (2,-1))
t[0]=1024
t
t_reshaped

tensor([1024,    1,    5,    4,    7,    0,    6,    2])

tensor([[1024,    1,    5,    4],
        [   7,    0,    6,    2]])

**torch.transpose()**

交换张量的两个维度

input: 要交换的张量

dim0： 要交换的维度

dim1： 要交换的维度

**torch.t()**

2维张量转置，对矩阵而言，等价于

torch.t(input, 0, 1)

In [20]:
t = torch.rand(2,3,4)
t_transposed = torch.transpose(t, dim0=1, dim1=2)
t.shape
t_transposed.shape

torch.Size([2, 3, 4])

torch.Size([2, 4, 3])

**torch.squeeze()**

压缩张量中长度为1的维度（轴）

dim:若为None, 移除所有长度为1的轴；若指定维度，当且仅当该轴长度为1时，可以被移除。

**torch.unsqueeze()**
依据dim扩展维度


In [21]:
t = torch.rand((1,2,3,1))
t_sq = torch.squeeze(t)
t_0 = torch.squeeze(t, dim=0)
t_1 = torch.squeeze(t, dim=1)
t.shape
t_sq.shape
t_0.shape
t_1.shape

torch.Size([1, 2, 3, 1])

torch.Size([2, 3])

torch.Size([2, 3, 1])

torch.Size([1, 2, 3, 1])

### 张量的数学运算

#### 加法

**torch.add(input, other, alpha, out=None)**

input: 第一个张量

alpha: 乘项因子

other: 第二个张量

**torch.addcdiv(input, value = 1, tensor1, tensor2, out=None) **

$ out_i = input_i + value \times \cfrac{tensor1_i}{tensor2_i} $ 

**torch.addcmul(input, value = 1, tensor1, tensor2, out=None) **

$ out_i = input_i + value \times tensor1_i \times tensor2_i $ 

In [22]:
t_0 = torch.randn((3,3))
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0, t_1)
t_add2 = torch.add(t_0,t_1,alpha=10)

t_0
t_1
t_add
t_add2

tensor([[-0.7966, -0.4545, -0.2147],
        [ 2.2404,  1.2458,  0.4775],
        [-2.1236,  0.8209, -0.6703]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[ 0.2034,  0.5455,  0.7853],
        [ 3.2404,  2.2458,  1.4775],
        [-1.1236,  1.8209,  0.3297]])

tensor([[ 9.2034,  9.5455,  9.7853],
        [12.2404, 11.2458, 10.4775],
        [ 7.8764, 10.8209,  9.3297]])

### 线性回归

求解步骤：

1. 确定模型Model

$ y = wx + b$

2. 选择损失函数

MSE

$ \cfrac{1}{m}\sum_{i=1}^m（y_i - \hat y_i)^2 $

3. 求解梯度并更新$w, b$

$ w = w - LR \times w.grad $

$ b = b = LR \times w.grad $

In [23]:
import torch
import matplotlib.pyplot as plt

torch.manual_seed(10)

lr = 0.1

# create training data
x = torch.rand(20, 1) * 10    # x data (tensor)
y = 2 * x + (5 + torch.randn(20,1)) # y data (tensor)

w = torch.randn((1), requires_grad = True)
b = torch.zeros((1), requires_grad = True)

for iteration in range(1000):
    # forward propagation
    wx = torch.mul(w, x)
    y_pred = torch.add(wx, b)
    
    # calculate loss
    loss = (0.5 * (y-y_pred)** 2).mean()
    
    # backward propagation
    loss.backward()

    # update para
    b.data.sub_(lr * b.grad)
    w.data.sub_(lr * w.grad)
    
    # drawing
#     if iteration % 20 == 0:
#             plt.scatter(x.data.numpy(), y.data.numpy())
#             plt.plot(x.data.numpy(), y_pred.data.numpy())
#             plt.text(2,20, 'Loss=%.4f' % loss.data.numpy())
#             plt.xlim(1.5, 10)
#             plt.ylim(8, 28)
#             plt.title('Iteration:{}\n w:{} b: {}'.format(iteration, w.data.numpy(), b.data.numpy()))
#             plt.pause(0.5)
            
    if loss.data.numpy() < 1:
        break

print('Iteration:{}\n w:{} b: {} loss: {}'.format(iteration, w.data.numpy(), b.data.numpy(), loss.data.numpy()))

tensor([0.3637])

tensor([4.1880])

tensor([0.0147])

tensor([1.3747])

tensor([0.5249])

tensor([3.5258])

tensor([0.6680])

tensor([3.1058])

tensor([0.6593])

tensor([1.4534])

tensor([1.4023])

tensor([4.1478])

tensor([1.3507])

tensor([1.6936])

tensor([1.8505])

tensor([2.3982])

tensor([2.4668])

tensor([3.6116])

tensor([2.4750])

tensor([0.9037])

tensor([3.3536])

tensor([3.4051])

tensor([3.6483])

tensor([2.1973])

tensor([3.9894])

tensor([1.1939])

Iteration:12
 w:[1.193853] b: [3.9894037] loss: 0.6023467183113098


### Computation Graph

In [26]:
import torch

w = torch.tensor([1.], requires_grad = True)
x = torch.tensor([2.], requires_grad = True)

a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a,b)

y.backward()
w.grad

# check is_leaf
print("is_leaf: \n", w.is_leaf, x.is_leaf, a.is_leaf, b.is_leaf, y.is_leaf)

# check grad
print("grad_fn: \n", w.grad, x.grad, a.grad, b.grad, y.grad)

tensor([5.])

is_leaf: 
 True True False False False
grad_fn: 
 tensor([5.]) tensor([2.]) None None None


<ipython-input-26-e19a38a0d7c2>:17: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print("grad_fn: \n", w.grad, x.grad, a.grad, b.grad, y.grad)
