## Numpy 库

### 为什么要用Numpy

#### 低效的python for循环

【例】求100万个数的导数

In [1]:
def compute_reciprocals(values):
    res = []
    for value in values:
        res.append(1/value)    # 每遍历到一个元素，要判断其类型，并查找适用于该数据类型的正确函数
    return res 

values = list(range(1, 1000001))
%timeit compute_reciprocals(values)

161 ms ± 30.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


%timeit: ipython中统计运行时间的魔术方法

In [2]:
import numpy as np

values = np.arange(1, 1000001)
%timeit 1/values

5.87 ms ± 479 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**实现相同的计算，Numpy的运行速度是for循环的近30倍，产生了质的飞跃。**

#### Numpy为何如此高效

**Numpy由C语言编写。**

**1. 解释性语言 vs. 编译性语言**

C 语言执行前，对代码进行整体编译，执行速度更快。

**2. 连续单一类型存储 vs. 分散多变类型存储**

(1) Numpy数组内的数据类型必须是统一的，如同为浮点型，而Python中的列表，元组等可以存储不同类型数据。

(2) Numpy数组内的数据**连续存储在内存中**，而Python列表的数据则**分散在内存中**。

这种存储结构，与一些更加高效的底层处理方式更加契合。

**3. 多线程 vs.线程锁**

Python语言执行时有线程锁，无法实现真正的多线程并行，C无此限制。

#### 什么时候用Numpy

**在数据处理过程中，遇到使用“Python for循环”解决一些向量化、矩阵化操作的时候，可以用Numpy**

如： 两个向量的点积、矩阵乘法

### Numpy数组的创建

#### 从列表开始创建

In [3]:

arr = np.array([1,2,3,4,5])
print(arr) 
print(type(arr))
print(type(arr[0]))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int32'>
(5,)


- 设置数组的数据类型

In [4]:
arr = np.array([1,2,3,4,5,6], dtype="float64")
print(arr)
print(type(arr[0]))
print(arr.size)

[1. 2. 3. 4. 5. 6.]
<class 'numpy.float64'>
6


- 检查数组占用的内存空间大小

In [5]:
import sys

print("total size of arr: {}".format(sys.getsizeof(arr)))
print("unit size of arr: {}".format(sys.getsizeof(arr[0])))

total size of arr: 144
unit size of arr: 32


sys.getsizeof() 函数返回的是这个对象所占用的空间大小，对于数组来说，除了数组中每个值占用空间外，数组对象还会存储数组长度、数组类型等其他信息。

而如果只想要获取数组中存储的值的占用空间大小，可以使用 numpy.ndarray.nbytes ，使用 numpy.ndarray.itemsize 获取数组中每个值的占用空间大小。

In [6]:
print("total size of arr: {}".format(arr.nbytes))
print("unit size of arr: {}".format(arr.itemsize))

total size of arr: 48
unit size of arr: 8


- 二维数组

In [7]:
d_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(d_2)
print(d_2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


#### 从头创建数组

（1） 创建长度为5的数组，值都为0

In [8]:
np.zeros(5, dtype=np.int64)

array([0, 0, 0, 0, 0], dtype=int64)

（2） 创建一个2*4的浮点型数组，值都为1

In [9]:
np.ones((2,4), dtype=np.float).itemsize

8

(3) 创建一个3*3的浮点数据，值都为8.8

In [10]:
np.full((3,3), 8.8)

array([[8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8]])

(4) 创建一个3*3的单位矩阵

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

(5) 创建一个线性序列数组，从1开始到15， 间隔2 \[1,15)

In [12]:
np.arange(1, 15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

(6) 创建一个4个元素的数组，这四个数均匀分配到\[0,1]

In [13]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

(7) 创建一个10个元素的数组，形成1 - 10^9的等比数列

In [14]:
np.logspace(0, 9, 10)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09])

(8) 创建一个3*3的，在0-1之间均匀分布的随机数构成的数组

In [15]:
np.random.random((3,3))

array([[0.62025574, 0.20110696, 0.11482395],
       [0.17263682, 0.12064455, 0.53011882],
       [0.05506051, 0.73181303, 0.94670669]])

(9) 创建一个3*3的，均值为0， 标准差为1的正态分布随机数构成的数组


In [16]:
np.random.normal(0, 1, (3,3))

array([[-0.4411268 , -0.81795752,  0.85903975],
       [ 0.83745093,  0.27997838,  1.12946024],
       [ 0.71774846, -0.365301  ,  0.11456006]])

(10) 创建一个3*3的，在\[0,10)之间随机整数构成的数组

In [17]:
np.random.randint(0, 10, (3,3))

array([[2, 1, 9],
       [5, 7, 4],
       [2, 9, 7]])

(10) 随机重排列


In [18]:
arr = np.array([10,20,30,40,50])
np.random.permutation(arr)    #产生新数组

array([20, 10, 40, 50, 30])

In [19]:
print(arr)   
np.random.shuffle(arr)    #改变原数组
print(arr)

[10 20 30 40 50]
[40 20 30 50 10]


（11）随机采样

- 按指定形状采样

In [20]:
arr = np.arange(10,25, dtype=np.float)
arr 

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24.])

In [21]:
np.random.choice(arr, size=(4,4))

array([[24., 15., 11., 18.],
       [15., 17., 17., 19.],
       [16., 11., 20., 16.],
       [10., 24., 13., 13.]])

- 按概率采样

In [22]:
np.random.choice(arr, size=(4,4), p=arr/sum(arr))

array([[15., 22., 18., 19.],
       [24., 15., 22., 19.],
       [18., 20., 22., 24.],
       [18., 13., 15., 13.]])

### Numpy数组的性质

#### 数组的属性

In [23]:
arr = np.random.randint(0, 10, (3,4))
arr 

array([[6, 2, 8, 4],
       [1, 8, 1, 0],
       [7, 1, 0, 4]])

In [24]:
print(arr.shape)    #数组形状
print(arr.ndim)     #数组维度

(3, 4)
2


In [25]:
y = np.arange(0, 10)
y.ndim

1

In [26]:
print(arr.size)    #数组大小，有多少个元素
print(arr.dtype)   #数组的数据类型
print(arr.itemsize) #每个元素所占内存空间的大小
print(arr.nbytes)   #数组所占内存空间的大小

12
int32
4
48


#### 数组索引

1. 一维数组索引

In [27]:
arr1 = np.arange(0, 10)
arr1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
print(arr1[0])
print(arr1[-1])

0
9


2. 多维数组索引 - 以二维为例


In [29]:
arr2 = np.random.randint(0, 20, size=(3,3))
arr2 

array([[ 6, 18,  6],
       [18, 17, 15],
       [12,  3, 14]])

In [30]:
print(arr2[0,0])
print(arr2[1][1])

6
17


Numpy 数组的数据类型固定，当整形数组插入浮点数时，浮点数会向下取整

In [31]:
arr2[2,2] = 1.678
arr2 

array([[ 6, 18,  6],
       [18, 17, 15],
       [12,  3,  1]])

#### 数组的切片

1. 一维数组，跟列表一样

In [32]:
print(arr1[:3])
print(arr1[3:])
print(arr1[::-1])

[0 1 2]
[3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


2. 多维数组 - 以二维为例


In [33]:
arr2 = np.random.randint(0,20, size=(3,4))
arr2 

array([[12,  4, 10,  2],
       [19,  1, 10,  9],
       [13, 16,  2,  9]])

In [34]:
arr2[:2, :3]

array([[12,  4, 10],
       [19,  1, 10]])

In [35]:
arr2[::-1,::-1]

array([[ 9,  2, 16, 13],
       [ 9, 10,  1, 19],
       [ 2, 10,  4, 12]])

（3） 获取数组的行和列

In [36]:
arr2

array([[12,  4, 10,  2],
       [19,  1, 10,  9],
       [13, 16,  2,  9]])

In [37]:
arr2[1, :]    #获取第一行，从0开始计数

array([19,  1, 10,  9])

In [38]:
arr2[1]    #获取第一行简写

array([19,  1, 10,  9])

In [39]:
arr2[:,2]    #获取第二列，从0开始计数

array([10, 10,  2])

（4） **切片获取的是视图，而非副本**

In [40]:
arr4 = np.random.randint(20, size=(3,4))
arr4 

array([[ 5, 19, 14, 18],
       [16, 18, 19,  1],
       [ 0, 16,  9,  1]])

In [41]:
arr5 = arr4[:2,:2]
arr5 

array([[ 5, 19],
       [16, 18]])

**注意：视图元素发生修改，则原数组亦发生相应的修改**

In [42]:
arr5[0][0] = 0
arr5

array([[ 0, 19],
       [16, 18]])

In [43]:
arr4 

array([[ 0, 19, 14, 18],
       [16, 18, 19,  1],
       [ 0, 16,  9,  1]])

**修改切片的安全方式: copy**

In [44]:
arr4 = np.random.randint(20, size=(3,4))
arr4 

array([[19, 16, 18,  2],
       [18,  2, 17,  6],
       [ 7,  4, 12, 12]])

In [45]:
arr6 = arr4[:2, :2].copy()
arr6 

array([[19, 16],
       [18,  2]])

In [46]:
arr6[0][0]=0
arr6

array([[ 0, 16],
       [18,  2]])

In [47]:
arr4

array([[19, 16, 18,  2],
       [18,  2, 17,  6],
       [ 7,  4, 12, 12]])

#### 数组的变形


In [48]:
arr5 = np.random.randint(0, 10, size=(12,))
arr5

array([5, 1, 0, 2, 4, 3, 2, 7, 4, 1, 4, 2])

In [49]:
arr5.shape 

(12,)

In [50]:
arr6 = arr5.reshape(3,4)
arr6

array([[5, 1, 0, 2],
       [4, 3, 2, 7],
       [4, 1, 4, 2]])

**注意：reshape返回的是视图，而非副本

In [51]:
arr6[0][0] = 6
arr6 

array([[6, 1, 0, 2],
       [4, 3, 2, 7],
       [4, 1, 4, 2]])

In [52]:
arr5 

array([6, 1, 0, 2, 4, 3, 2, 7, 4, 1, 4, 2])

可以用np.reshape().copy()的方法生成一个副本

In [53]:
arr5 = np.random.randint(0, 10, size=(12,))
arr5

array([2, 5, 5, 7, 7, 9, 5, 1, 2, 4, 0, 5])

In [54]:
arr7 = arr5.reshape(3,4).copy()
arr7

array([[2, 5, 5, 7],
       [7, 9, 5, 1],
       [2, 4, 0, 5]])

In [55]:
arr7[0][0]=8
arr7

array([[8, 5, 5, 7],
       [7, 9, 5, 1],
       [2, 4, 0, 5]])

In [56]:
arr5 

array([2, 5, 5, 7, 7, 9, 5, 1, 2, 4, 0, 5])

**一维向量转行向量**

In [57]:
arr6 = arr5.reshape(1, arr5.shape[0])
arr6

array([[2, 5, 5, 7, 7, 9, 5, 1, 2, 4, 0, 5]])

In [58]:
print(arr6.shape)    #注意和一维数组的区别
print(arr6.ndim)     #注意这里是2为数组了，而不是一维数组了

(1, 12)
2


In [59]:
arr7 = arr5[np.newaxis, :]    # 转行向量的另一个方式
arr7

array([[2, 5, 5, 7, 7, 9, 5, 1, 2, 4, 0, 5]])

**一维向量转列向量**

In [60]:
arr8 = arr5.reshape(arr5.shape[0],1)
arr8 

array([[2],
       [5],
       [5],
       [7],
       [7],
       [9],
       [5],
       [1],
       [2],
       [4],
       [0],
       [5]])

In [61]:
print(arr8.shape)
print(arr8.ndim)

(12, 1)
2


In [62]:
arr8 = arr5[:,np.newaxis]    #转列向量的另一个方式
arr8

array([[2],
       [5],
       [5],
       [7],
       [7],
       [9],
       [5],
       [1],
       [2],
       [4],
       [0],
       [5]])

**多维向量转一维向量**

In [63]:
arr6 = np.random.randint(0,10, size=(3,4))
arr6 

array([[0, 1, 2, 3],
       [6, 8, 7, 8],
       [9, 4, 4, 1]])

- flatten()返回的是副本

In [64]:
arr7 = arr6.flatten()
arr7

array([0, 1, 2, 3, 6, 8, 7, 8, 9, 4, 4, 1])

In [65]:
arr7[0]=11
arr7 

array([11,  1,  2,  3,  6,  8,  7,  8,  9,  4,  4,  1])

In [66]:
arr6 

array([[0, 1, 2, 3],
       [6, 8, 7, 8],
       [9, 4, 4, 1]])

- ravel()返回的是视图

In [67]:
arr8 = arr6.ravel()
arr8

array([0, 1, 2, 3, 6, 8, 7, 8, 9, 4, 4, 1])

In [68]:
arr8[0]=11
arr8

array([11,  1,  2,  3,  6,  8,  7,  8,  9,  4,  4,  1])

In [69]:
arr6 

array([[11,  1,  2,  3],
       [ 6,  8,  7,  8],
       [ 9,  4,  4,  1]])

- reshape返回的是视图

In [70]:
arr6 = np.random.randint(0,10, size=(3,4))
arr6 

array([[0, 5, 6, 5],
       [2, 4, 0, 7],
       [0, 7, 5, 8]])

In [71]:
arr9 = arr6.reshape(-1)
arr9

array([0, 5, 6, 5, 2, 4, 0, 7, 0, 7, 5, 8])

In [72]:
arr9[0]=11
arr9 

array([11,  5,  6,  5,  2,  4,  0,  7,  0,  7,  5,  8])

In [73]:
arr6 

array([[11,  5,  6,  5],
       [ 2,  4,  0,  7],
       [ 0,  7,  5,  8]])

#### 数组的拼接

In [74]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,17).reshape(2,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


1. 水平拼接 - 副本

In [75]:
arr3 = np.hstack([arr1, arr2])
arr3

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [76]:
arr3[0][0]=0
arr3 

array([[ 0,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [77]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# 水平拼接的另一个方法
arr4 = np.c_[arr1, arr2]
arr4

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [79]:
arr4[0][0]=0
arr4 

array([[ 0,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

2. 垂直拼接 - 副本

In [81]:
arr5 = np.vstack([arr1, arr2])
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [82]:
arr6 = np.r_[arr1, arr2]
arr6 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

#### 数组的分裂

##### split的用法

In [83]:
arr1 = np.arange(10)
arr1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr2, arr3, arr4 = np.split(arr1, [2,7])    # 在数组第二，第7个位置前面分裂
arr2, arr3, arr4 

(array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9]))

##### hsplit的用法

In [85]:
arr1 = np.arange(1, 26).reshape(5,5)
arr1 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
left, middle, right = np.hsplit(arr1, [2,4])
print("Left: \n", left)
print("Middle: \n", middle)
print("Right: \n", right)

Left: 
 [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
Middle: 
 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
Right: 
 [[ 5]
 [10]
 [15]
 [20]
 [25]]


##### vsplit的用法

In [87]:
arr1 = np.arange(1, 26).reshape(5,5)
arr1 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [88]:
upper, middle, lower = np.vsplit(arr1, [2,4])
print("Uppder:\n", upper)
print("Middle:\n", middle)
print("Lower:\n", lower)

Uppder:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Middle:
 [[11 12 13 14 15]
 [16 17 18 19 20]]
Lower:
 [[21 22 23 24 25]]


### Numpy 四大运算

#### 向量化运算

- 与数字的加减乘除等

In [89]:
arr1 = np.arange(1,6)
arr1 

array([1, 2, 3, 4, 5])

In [90]:
print("arr1 + 5: ",arr1 + 5)
print("arr1 - 5: ",arr1 - 5)
print("arr1 * 5: ",arr1 * 5)
print("arr1 / 5: ",arr1 / 5)

arr1 + 5:  [ 6  7  8  9 10]
arr1 - 5:  [-4 -3 -2 -1  0]
arr1 * 5:  [ 5 10 15 20 25]
arr1 / 5:  [0.2 0.4 0.6 0.8 1. ]


In [91]:
print("-arr1: ", -arr1)
print("arr1 ** 2: ",arr1 ** 2)
print("arr1 // 5: ",arr1 // 5)
print("arr1 % 5: ",arr1 % 5)

-arr1:  [-1 -2 -3 -4 -5]
arr1 ** 2:  [ 1  4  9 16 25]
arr1 // 5:  [0 0 0 0 1]
arr1 % 5:  [1 2 3 4 0]


- 绝对值、三角函数、指数、对数

In [92]:
arr1 = np.array([-1,2,-3,4,-5,6])
arr1 

array([-1,  2, -3,  4, -5,  6])

In [93]:
np.abs(arr1)

array([1, 2, 3, 4, 5, 6])

In [94]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [95]:
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

- 三角函数

In [96]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [97]:
print("sin(theta): ", np.sin(theta))
print("cos(theta): ", np.cos(theta))
print("tan(theta): ", np.tan(theta))

sin(theta):  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta):  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta):  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [98]:
arr1 = [-1, 0, 1]
print("arcsin(theta): ", np.arcsin(theta))
print("arccos(theta): ", np.arccos(theta))
print("arctan(theta): ", np.arctan(theta))

arcsin(theta):  [ 0. nan nan]
arccos(theta):  [1.57079633        nan        nan]
arctan(theta):  [0.         1.00388482 1.26262726]


<ipython-input-98-abb544a9186d>:2: RuntimeWarning: invalid value encountered in arcsin
  print("arcsin(theta): ", np.arcsin(theta))
<ipython-input-98-abb544a9186d>:3: RuntimeWarning: invalid value encountered in arccos
  print("arccos(theta): ", np.arccos(theta))


#### 矩阵运算

In [99]:
m = np.arange(9).reshape(3,3)
m 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
# 转置
m.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [101]:
# 矩阵乘法

m = np.array([[0, 1], [2, 3]])
n = np.array([[1, 0], [3, 2]])


In [102]:
m.dot(n)

array([[ 3,  2],
       [11,  6]])

In [103]:
np.dot(m, n)

array([[ 3,  2],
       [11,  6]])

In [104]:
n.dot(m)

array([[0, 1],
       [4, 9]])

In [105]:
np.dot(n, m)

array([[0, 1],
       [4, 9]])

注意和 m * n 的区别


In [106]:
m * n 

array([[0, 0],
       [6, 6]])

#### 广播运算

In [107]:
arr1 = np.arange(3).reshape(1,3)
arr1

array([[0, 1, 2]])

In [108]:
arr1 + 5

array([[5, 6, 7]])

**规则**

如果两个数组形状在维度上不匹配，

那么数组的形式会沿着维度为1的维度进行扩展以匹配另一个数组

In [111]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
arr2 = np.arange(3).reshape(1,3)
arr2

array([[0, 1, 2]])

In [113]:
arr1 + arr2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [114]:
arr3 = np.logspace(1, 10, 10, base=2).reshape(2, 5)
arr3

array([[   2.,    4.,    8.,   16.,   32.],
       [  64.,  128.,  256.,  512., 1024.]])

In [120]:
arr4 = np.array([[1,2,4,8,16]])
arr4

array([[ 1,  2,  4,  8, 16]])

In [121]:
arr3 / arr4 

array([[ 2.,  2.,  2.,  2.,  2.],
       [64., 64., 64., 64., 64.]])

In [127]:
arr5 = np.ones((3,1))
arr6 = np.arange(3).reshape(1,3)

In [128]:
arr5

array([[1.],
       [1.],
       [1.]])

In [129]:
arr6

array([[0, 1, 2]])

In [131]:
arr5+arr6  #将 1x3 和 3x1 的 向量都扩展为 3x3 的矩阵

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

#### 比较运算和掩码

##### 比较运算

In [135]:
arr1 = np.random.randint(1, 100, size=(10,10))
arr1 > 50

array([[ True, False,  True, False, False,  True, False, False,  True,
        False],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False],
       [ True, False, False,  True, False, False,  True,  True, False,
         True],
       [False,  True, False, False, False, False, False, False,  True,
        False],
       [ True, False,  True,  True, False,  True,  True, False,  True,
         True],
       [ True, False, False, False, False, False,  True,  True,  True,
        False],
       [False,  True, False, False, False, False,  True, False,  True,
        False],
       [False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [ True,  True, False,  True,  True,  True, False,  True,  True,
         True],
       [False, False,  True, False,  True,  True, False, False, False,
         True]])

##### 操作布尔数组

In [145]:
arr2 = np.random.randint(10, size=(2,5))
arr2

array([[9, 9, 8, 5, 8],
       [4, 7, 8, 0, 6]])

In [138]:
print(arr2 > 5)
np.sum(arr2 > 5)

[[ True False  True  True  True]
 [ True False False  True False]]


6

In [139]:
np.all(arr2 > 0)

True

In [141]:
np.any(arr2 == 6)    #至少有一个等于6

True

In [146]:
np.all(arr2 < 9, axis = 1)    #按行进行判断，是否每行的元素都小于9

array([False,  True])

In [147]:
np.all(arr2 > 3, axis = 0)    #按列进行判断，是否每列的元素都大于3

array([ True,  True,  True, False,  True])

In [148]:
(arr2 < 9) & (arr2 > 5)    #小于9，大于5的数

array([[False, False,  True, False,  True],
       [False,  True,  True, False,  True]])

In [149]:
np.sum((arr2 < 9) & (arr2 > 5))

5

##### 将布尔数组作为掩码

In [154]:
arr1 = np.random.randint(1, 10, size=(3,4))
arr1

array([[5, 6, 8, 5],
       [9, 6, 2, 3],
       [2, 3, 1, 3]])

In [156]:
arr1 > 5

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [157]:
arr2[ arr2 > 5]

array([9, 9, 8, 8, 7, 8, 6])