### Diagnoal Matrix 对角矩阵

设A为n阶方阵，如果满足 $a_{ij} \neq 0， i=j; a_{ij}= 0, i\neq j$
称A为对角矩阵。

#### Identity 单位矩阵
设A为n阶方阵，如果满足 $a_{ij} = 1， i=j; a_{ij}= 0, i\neq j$
称A为单位矩阵。

### Transpose Matrix 转置矩阵

将矩阵的行转换维同序数的列得到的一个新矩阵，叫做A的**转置矩阵，记作$A^T$**。

$ A = \left[\begin{matrix}1 & 2 & 0 \cr 5 &-2 &7 \end{matrix}\right] $

$ A^T = \left[\begin{matrix} 1 & 5 \cr 2 & -2 \cr 0 & 7 \end{matrix}\right] $

### Symmetric Matrix 对称矩阵

设A为**n阶方阵**， 如果满足$A^T = A$，即 $a_{ij}=a_{ji} (i,j = 1,2,\cdots, n)$
称A为对称矩阵。它的元素以对角线为对称轴对应相等。

### 幂等矩阵

设A为**n阶方阵**， 如果满足$A^2 = A$，即 A 为幂等矩阵

### 可逆矩阵
对矩阵A,若$\exists B使得 BA = I $, 称A为可逆矩阵，且$ B=A^{-1}$

### Singular 奇异矩阵、non-singular非奇异矩阵
当$\mid A\mid =0$时，称A为**奇异矩阵**，否则称为**非奇异矩阵**。

A 为可逆矩阵$\Leftarrow \Rightarrow \mid A\mid \neq 0$

### Orthogonal Matrix 正交矩阵
如果n阶矩阵A 满足$A^TA = I$, 即$A^{-1}=A^T$,那么称A为正交矩阵。

https://blog.csdn.net/weixin_43233770/article/details/83039369?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162260017016780357246017%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=162260017016780357246017&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-4-83039369.first_rank_v2_pc_rank_v29&utm_term=%E6%AD%A3%E4%BA%A4%E7%9F%A9%E9%98%B5%E4%B8%8E%E6%AD%A3%E5%AE%9A%E7%9F%A9%E9%98%B5%E5%8C%BA%E5%88%AB&spm=1018.2226.3001.4187

### 特征分解 Eigendecomposition

#### 矩阵的特征值和特征向量

An **eigenvector of a square matrix A** is a non-zero vector $v$ such that:

$$ Av = \lambda v$$

The scalar $\lambda$ is known as the **eigenvalue** corresponding to this eigenvector. 

Suppose that a matrix $A$ has $n$ linearly independent eigenvectors ${v^{(1)}, v^{(2)},\cdots,v^{(n)}}$, 

with corresponding eigenvalues ${\lambda_1, \lambda_2,\cdots, \lambda_n}$. We may concatenate all of the

eigenvectors to form a matrix $V$ with one eigenvector **per column**: $V=[v^{(1)}, v^{(2)},\cdots,v^{(n)}]$.

Likewise, we can concatenate the eigenvalues to form a vector $\lambda = [\lambda_1, \lambda_2,\cdots, \lambda_n]^T$

The **特征分解 eigendecomposition of A** is then given by

$$ A = V diag(\lambda)V^{-1} $$

**Not every matrix can be decomposed into eigenvalues and eigenvectors**. In some cases, the decomposition exists, but may involve complex rather than real numbers.

#### 对称矩阵的特征分解

**Every real symmetric matrix can be decomposed into an expression using only real-valued eigenvectors and eigenvalues**:

$$ A = Q\Lambda Q^T $$

where Q is an **Orthogonal matrix 正交矩阵** composed of eigenvectors of A, and $\Lambda$ is a **diagonal matrix 对角矩阵**.

The eigenvalue $\Lambda_{i,i}$ is associated with the eigenvector in column i of Q, denoted as $Q_{:,i}$.

**任何一个对称矩阵A 都有特征分解，但特征分解并不唯一**。通常将$\Lambda$中的数降序排列。在这种情况下，如果特征值都不相同，特征分解唯一。

#### 正定、半正定、负定、半负定矩阵

A matrix whose eigenvalues are all positive is called **正定矩阵positive definite matrix**. 

A matrix whose eigenvalues are all positive **or zero-valued** is called **半正定positive semidefinite matrix**.

Likewise, if all eigenvalues are negative, the matrix is **负定矩阵negative definite**, and if all eigenvalues 

are negative or zero-valued, it is **半负定negative semidefinite**.

Positive semidefinite matrices: $\forall x, x^TAx \geq 0$ 

Positive definite matrics additionally guarantees that $x^TAx = 0 \Rightarrow x=0$

### 奇异值分解Singular Value Decomposition 

参考资料：
> https://mp.weixin.qq.com/s/I0Pb6pPYVIW02_Oxkcsfng

The **singular value decomposition (SVD)** provides another way to factorize a matrix into **singular vectors** and **singular values**.

The SVD allows us to discover some of the same kind of information as the **eigencomposition**. However, SVD is more generally applicable.

**Every real matrix has a singular value decomposition**, but the same is not true of the eigenvalue decomposition. For example, if a matrix is not square, the eigendecomposition is not defined, and we must use a singular value decomposition instead.

Suppose that A is an $m\times n$ matrix. We will write A as a product of three matrices:

$$ A = UDV$$

$U$ is defined to be an $m\times m$ matrix, $D$ is defined to be an $m\times n$ matrix, and$V$ is defined to be an $n\times n$ matrix.

**The matrices U and V are both defined to be orthogonal matrices**. The matrix D is defined to be **a diagonal matrix. Note that D is not necessarily square**.

> D 又写为Sigma, $\Sigma$, 一个$m\times n$ 的对角矩阵。
“Introduction to Linear Algebra", 2016, p371

The elements along the diagonal of D are known as the **singular values** of the matrix A. The columns of U are known as the **left-singular vectors**. The columns of V are known as as the **right-singular vectors**.

The left-singular vectors of A are the eigenvectors of $AA^T$. The right-singular vectors of A are the eigenvectors of $A^TA$. The non-zero singular values of A are the square roots of the eigenvalues of $A^TA$. The same is true for $AA^T$.

Perhaps the most useful feature of the SVD is that we can use it to partially generalize matrix inversion to non-square matrices, as we will see in the next section？

> How to understand this sentence?

---

SVD是通过迭代式的数值方法计算的（具体计算暂时略去）。**每一个矩形矩阵都有一个奇异值分解，尽管所得到的矩阵可能包含复数值以及浮点算术的局限性可能导致某些举行无法简单利落地完成分解**。

**SVD**让我们可以发现某些与**特征分解**同类型的信息。但是,SVD又更广的适用性。

**SVD**在矩阵求逆等其它矩阵计算有广泛的应用，但也可用作机器学习中的数据归约方法。SVD也可用在最小二乘线性回归，图像压缩和数据去噪中。

---

#### 计算奇异值分解

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd 

A = array([[1,2],[3,4],[5,6]])
A 
U, s, V = svd(A)
U
s
V 

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

array([9.52551809, 0.51430058])

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

#### 根据SVD重建矩阵
svd()返回的U, s, V元素不能直接相乘。

s向量必须使用diag()函数转换成对角矩阵。默认情况下，这个函数将创建一个相对于原来矩阵的 m x m 的方形矩阵。

创建了方形的Sigma对角矩阵后，各个矩阵的大小与我们分解的原始 n x m 矩阵是相关的。

$$ U (m\times m),\Sigma(m \times m), V^T(n \times n)$$

而事实上，我们需要：

$$ U (m\times m),\Sigma(m \times n), V^T(n \times n)$$

可以通过创建一个全是0值的 m x n 的新 $\Sigma$ 矩阵（比如，更多行）并使用通过diag()计算得到的方形对角矩阵来填充矩阵的前 n x n 部分

In [3]:
# Reconstruct SVD
from numpy import array, diag, dot, zeros
# from numpy import diag
# from numpy import dot
# from numpy import zeros
from scipy.linalg import svd 

A = array([[1,2],[3,4],[5,6]])
A, A.shape
# Singular-Value Decomposition
U, s, V = svd(A)
U, s, V
# Create an m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# Populate Sigma with n x n diagnoal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
U.shape, Sigma.shape, V.shape
Sigma
B = U.dot(Sigma.dot(V))
B

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

((3, 3), (3, 2), (2, 2))

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [4]:
# square matrix
from numpy import array, diag, dot, zeros
# from numpy import diag
# from numpy import dot
# from numpy import zeros
from scipy.linalg import svd 

A = array([[1,2,3],[4,5,6],[7,8,9]])
A, A.shape
# Singular-Value Decomposition
U, s, V = svd(A)
U, s, V
# Create an m x n Sigma matrix
Sigma = diag(s)
Sigma
# reconstruct matrix
B = U.dot(Sigma.dot(V))
B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.33475287e-16]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### 用于伪逆的SVD

伪逆(pseudoinverse)是将方形矩阵的矩形求逆泛化应用到行数和列数不等的矩形矩阵上。这也被称为广义逆(Generalized inverse) 或摩尔-彭若斯逆(Moore-Penrose Inverse)。

伪逆表示为$A^+$

伪逆式使用A的奇异值分解计算的

$$A^+ = V\cdot D^+ \cdot U^T$$

其中，$A^+$是A的**伪逆**，$D^+$是对角矩阵Sigma的**伪逆**，$U^T$是U的**转置**。

> 可以根据svd运算得到U和V。
> 根据Sigma创建一个对角矩阵，计算Sigma中每个非零元素的倒数，就可以得到$D^+$,如下：
>
$ Sigma = \left[\begin{matrix} s11 & 0 & 0 \cr 0 & s22 & 0 \cr 0 & 0 & s33 \end{matrix}\right] $
>
$D^+ =$ $ \left[\begin{matrix} \cfrac{1}{s11} & 0 & 0 \cr 0 & \cfrac{1}{s22} & 0 \cr 0 & 0 & \cfrac{1}{s33} \end{matrix}\right] $

伪逆提供了一种求解线性回归方程的方法，尤其是当**行数多于列数**时，而这也是很常见的情况。

Numpy提供了函数pinv()来计算矩形的伪逆。


In [5]:
#pseudoinverse
from numpy import array
from scipy.linalg import pinv
#define array
A = array([[1,2],[3,4],[5,6],[7,8]])
A 
#calculate pseudoinverse
B = pinv(A)
B 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[-1.00000000e+00, -5.00000000e-01,  8.64905778e-17,
         5.00000000e-01],
       [ 8.50000000e-01,  4.50000000e-01,  5.00000000e-02,
        -3.50000000e-01]])

可以通过svd采用人工的方式计算伪逆，并将结果与pinv()函数的结果进行比较。
具体实现方式为：
$$ A^+ = V^T \cdot D^T \cdot U^T$$

In [6]:
#pseudoinverse through svd
from numpy import array, zeros, diag 
from scipy.linalg import svd 
#define matrix
A = array([[1,2],[3,4],[5,6],[7,8]])
A 
#calculate svd
U,s,V = svd(A)
#reciprocals of s
d = 1.0 / s
#create mxn matrix
D = zeros(A.shape)
#populate D with nxn diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
#calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
B 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[-1.00000000e+00, -5.00000000e-01,  2.20397652e-17,
         5.00000000e-01],
       [ 8.50000000e-01,  4.50000000e-01,  5.00000000e-02,
        -3.50000000e-01]])

#### 用于降维的svd

SVD的一大常见应用是降维。

具有大量特征的数据（比如特征数（列数）多于观察数（行数））也许可以被**归约**成与所涉预测问题最相关的**更小特征子集**。

其结果是一个秩更低的矩阵，<u>据说接近原始矩阵</u>。不知道这个“据说”是什么意思。

为了做到这一点，我们可以在原来的数据上执行一次 SVD 操作并**选择 Sigma 中前 k 个最大的奇异值**。这些**列可以从 Sigma 中选择得到，行可以从 $V^T$ 中选择得到**。

然后可以重建原始向量 A 的近似 B。

$ B = U \cdot Sigma(k) \cdot V^T(k)$

---

在自然语言处理中，这种方法可以被用在文档中词出现情况或词频的矩阵上，并被称为**隐含语义分析（Latent Semantic Analysis）或隐含语义索引（Latent Semantic Indexing）**。

在实践中，我们可以保留和使用被称为 T 的**描述性数据子集。这是矩阵的密集总结或投射**。

$T=U\cdot Sigma(k)$

此外，这种变换既可以在原来的矩阵 A 上计算和应用，也可以在其它类似的矩阵上计算和应用。

$T=V^T(k) \cdot A$

---

下面的示例是使用 SVD 的数据归约。

首先定义一个 3×10 的矩阵，其列数多于行数。然后计算 SVD 并且只选取其前两个特征。这些元素再重新结合起来，得到原始矩阵的准确再现。最后计算转换的方式有两种。

In [10]:
from numpy import array, diag, zeros
from scipy.linalg import svd
# create matrix, #column > # row
A = array([[1,2,3,4,5,6,7,8,9,10],
             [11,12,13,14,15,16,17,18,19,20],
             [21,22,23,34,35,36,27,28,29,30]])
# svd
U,s,V = svd(A)
U.shape,s.shape,V.shape 
#create a mxn Sigma matrix
Sigma = zeros(A.shape)
#populate Sigma with nxn diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
#select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements,:]
#reconstruct
B = U.dot(Sigma.dot(V))
B
#transform
T = U.dot(Sigma)
T
T = A.dot(V.T)
T

((3, 3), (3,), (10, 10))

array([[ 2.57279362,  3.35440288,  4.13601214,  3.43636548,  4.21797474,
         4.999584  ,  7.26244918,  8.04405844,  8.8256677 ,  9.60727696],
       [ 9.62974585, 10.82001291, 12.01027997, 14.49105142, 15.68131848,
        16.87158554, 16.77134821, 17.96161527, 19.15188233, 20.34214939],
       [21.4269724 , 22.36768502, 23.30839763, 33.84698794, 34.78770056,
        35.72841318, 27.0712481 , 28.01196072, 28.95267333, 29.89338595]])

array([[-18.20721501,  -6.76115284],
       [-49.39240188,  -6.28349004],
       [-91.44373766,   4.74016526]])

array([[-18.20721501,  -6.76115284],
       [-49.39240188,  -6.28349004],
       [-91.44373766,   4.74016526]])

scikit-learn 提供了直接实现这种功能的 TruncatedSVD 类。

TruncatedSVD 的创建必须指定所需的特征数或所要选择的成分数，比如 2。一旦创建完成，你就可以通过调用 fit() 函数来拟合该变换（比如：计算 $V^T(k)$），然后再通过调用 transform() 函数将其应用于原始矩阵。结果得到上面被称为 T 的 A 的变换。

下面的示例演示了 TruncatedSVD 类。

In [11]:
from numpy import array
from sklearn.decomposition import TruncatedSVD
# create matrix, #column > # row
A = array([[1,2,3,4,5,6,7,8,9,10],
             [11,12,13,14,15,16,17,18,19,20],
             [21,22,23,34,35,36,27,28,29,30]])
#svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
result

TruncatedSVD()

array([[18.20721501,  6.76115284],
       [49.39240188,  6.28349004],
       [91.44373766, -4.74016526]])

可以看到，结果得到的值与上面人工计算的结果一致，**但某些值的符号不一样**。由于所涉及的计算的性质以及所用的基础库和方法的差异，可以预见在符号方面会存在一些不稳定性。只要对该变换进行训练以便复用，这种不稳定性在实践中应该不成问题。